# Generated by Django 4.1 on 2022-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
