# Generated by Django 4.1 on 2022-09-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_todo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(db_column='_title', max_length=200),
        ),
    ]
