# Generated by Django 4.1 on 2022-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_todo_id_todo__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
