# Generated by Django 4.1 on 2022-09-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_todo__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='body',
        ),
    ]
