# Generated by Django 4.1 on 2022-09-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_todo__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='_id',
            new_name='id',
        ),
    ]
