# Generated by Django 4.1 on 2022-09-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename__id_todo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='_id',
        ),
    ]
