# Generated by Django 4.1 on 2022-09-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_title_todo_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='title',
        ),
    ]
