# Generated by Django 4.1 on 2022-09-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_id_todo__id'),
        ('api', '0018_rename_title_todo_body'),
    ]

    operations = [
    ]
