# Generated by Django 4.1 on 2022-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20220916_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
