# Generated by Django 4.1 on 2022-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_todo__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
