# Generated by Django 4.1 on 2022-09-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_todo_completed_todo_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='updatedAt',
        ),
    ]
