# Generated by Django 4.1 on 2022-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_created_todo_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
